# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeroomMainWindow.ui'
#
# Created: Tue Apr  9 01:40:07 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_TimeroomMainWindow(object):
    def setupUi(self, TimeroomMainWindow):
        TimeroomMainWindow.setObjectName("TimeroomMainWindow")
        TimeroomMainWindow.resize(950, 750)
        TimeroomMainWindow.setMinimumSize(QtCore.QSize(750, 550))
        self.centralWidget = QtGui.QWidget(TimeroomMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.dirView = QtGui.QTreeView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirView.sizePolicy().hasHeightForWidth())
        self.dirView.setSizePolicy(sizePolicy)
        self.dirView.setProperty("showDropIndicator", False)
        self.dirView.setObjectName("dirView")
        self.dirView.header().setVisible(False)
        self.tableView = QtGui.QTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        TimeroomMainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(TimeroomMainWindow)
        self.statusBar.setSizeGripEnabled(True)
        self.statusBar.setObjectName("statusBar")
        TimeroomMainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(TimeroomMainWindow)
        self.toolBar.setObjectName("toolBar")
        TimeroomMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Initialize = QtGui.QAction(TimeroomMainWindow)
        self.action_Initialize.setEnabled(False)
        self.action_Initialize.setObjectName("action_Initialize")
        self.action_Read = QtGui.QAction(TimeroomMainWindow)
        self.action_Read.setEnabled(False)
        self.action_Read.setStatusTip("")
        self.action_Read.setObjectName("action_Read")
        self.action_Process = QtGui.QAction(TimeroomMainWindow)
        self.action_Process.setEnabled(False)
        self.action_Process.setObjectName("action_Process")
        self.action_Exit = QtGui.QAction(TimeroomMainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtGui.QAction(TimeroomMainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Save = QtGui.QAction(TimeroomMainWindow)
        self.action_Save.setEnabled(False)
        self.action_Save.setStatusTip("")
        self.action_Save.setObjectName("action_Save")
        self.action_Process_Curves = QtGui.QAction(TimeroomMainWindow)
        self.action_Process_Curves.setCheckable(True)
        self.action_Process_Curves.setChecked(False)
        self.action_Process_Curves.setEnabled(True)
        self.action_Process_Curves.setObjectName("action_Process_Curves")
        self.action_Process_Gradients = QtGui.QAction(TimeroomMainWindow)
        self.action_Process_Gradients.setCheckable(True)
        self.action_Process_Gradients.setChecked(False)
        self.action_Process_Gradients.setEnabled(True)
        self.action_Process_Gradients.setObjectName("action_Process_Gradients")
        self.toolBar.addAction(self.action_Read)
        self.toolBar.addAction(self.action_Initialize)
        self.toolBar.addAction(self.action_Process_Curves)
        self.toolBar.addAction(self.action_Process_Gradients)
        self.toolBar.addAction(self.action_Process)
        self.toolBar.addAction(self.action_Save)
        self.toolBar.addAction(self.action_Exit)
        self.toolBar.addAction(self.action_About)

        self.retranslateUi(TimeroomMainWindow)
        QtCore.QMetaObject.connectSlotsByName(TimeroomMainWindow)

    def retranslateUi(self, TimeroomMainWindow):
        TimeroomMainWindow.setWindowTitle(QtGui.QApplication.translate("TimeroomMainWindow", "Timeroom", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("TimeroomMainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Initialize.setText(QtGui.QApplication.translate("TimeroomMainWindow", "&Initialize", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Initialize.setToolTip(QtGui.QApplication.translate("TimeroomMainWindow", "Auto-detect keyframes based on EV changes (discards existing ratings)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Read.setText(QtGui.QApplication.translate("TimeroomMainWindow", "&Read", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Read.setToolTip(QtGui.QApplication.translate("TimeroomMainWindow", "Read (or re-read) sidecar files, discarding any unsaved changes", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Process.setText(QtGui.QApplication.translate("TimeroomMainWindow", "&Process", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Process.setToolTip(QtGui.QApplication.translate("TimeroomMainWindow", "Interpolate values between keyframes", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("TimeroomMainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setIconText(QtGui.QApplication.translate("TimeroomMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setToolTip(QtGui.QApplication.translate("TimeroomMainWindow", "Exit without saving changes", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("TimeroomMainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setToolTip(QtGui.QApplication.translate("TimeroomMainWindow", "About Timeroom", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("TimeroomMainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setToolTip(QtGui.QApplication.translate("TimeroomMainWindow", "Write outstanding changes (ratings or interpolated settings) to sidecars", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Process_Curves.setText(QtGui.QApplication.translate("TimeroomMainWindow", "Interpolate Curves", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Process_Curves.setToolTip(QtGui.QApplication.translate("TimeroomMainWindow", "Whether to interpolate tone curves during process", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Process_Gradients.setText(QtGui.QApplication.translate("TimeroomMainWindow", "Interpolate Gradients", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Process_Gradients.setToolTip(QtGui.QApplication.translate("TimeroomMainWindow", "Whether to interpolate gradients during process", None, QtGui.QApplication.UnicodeUTF8))

